before_install: eval $(curl https://travis-perl.github.io/init) --auto
dist: trusty
language: perl
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.26.1-mb"
  - "5.26.1-thr"
  - "dev"
sudo: false
